import { Employee } from "./types";

export const INITIAL_EMPLOYEES: Employee[] = [
  // Executives
  {
    id: "arun",
    name: "ARUN G",
    role: "CEO",
    department: "Executives",
    photoUrl: "https://picsum.photos/seed/arun/100/100",
    managerId: null,
    color: "#FCD34D",
    displayOrder: 0,
    email: "arun@company.com",
    contact: "+91 98765 43210",
    joinDate: "2020-01-01",
  },
  {
    id: "padmavathy",
    name: "PADMAVATHY",
    role: "OPERATION HEAD",
    department: "Executives",
    photoUrl: "https://picsum.photos/seed/padma/100/100",
    managerId: "arun",
    color: "#FCD34D",
    displayOrder: 1,
    email: "padma@company.com",
    contact: "+91 98765 43211",
    joinDate: "2020-02-15",
  },
  {
    id: "ranganadin",
    name: "RANGANADIN.C",
    role: "CHIEF OPERATING OFFICER",
    department: "Executives",
    photoUrl: "https://picsum.photos/seed/ranganadin/100/100",
    managerId: "arun",
    color: "#FCD34D",
    displayOrder: 2,
    bio: "Optimizing workflows to ensure that cutting-edge IT services are delivered on time and exceed expectations.",
    joinDate: "2021-01-01",
  },
  {
    id: "cyrille",
    name: "CYRILLE HELENA",
    role: "OPERATION HEAD - CENTRAL AFRICA",
    department: "Executives",
    photoUrl: "https://picsum.photos/seed/cyrille/100/100",
    managerId: "arun",
    color: "#FCD34D",
    displayOrder: 3,
    bio: "Ensuring operational excellence and seamless IT service delivery across Central Africa.",
    joinDate: "2021-02-01",
  },
  {
    id: "akansha",
    name: "AKANSHA ARORA",
    role: "OPERATION HEAD - CENTRAL EUROPE",
    department: "Executives",
    photoUrl: "https://picsum.photos/seed/akansha/100/100",
    managerId: "arun",
    color: "#FCD34D",
    displayOrder: 4,
    bio: "Driving strategic growth and operational efficiency in the Central European market.",
    joinDate: "2021-03-01",
  },
  {
    id: "priyadharshini",
    name: "PRIYADHARSHINI M",
    role: "Operation lead",
    department: "Executives",
    photoUrl: "https://picsum.photos/seed/priya/100/100",
    managerId: "padmavathy",
    color: "#FCD34D",
    displayOrder: 5,
    email: "priya@company.com",
    contact: "+91 98765 43212",
    joinDate: "2021-03-10",
  },

  // IST ATHENA
  {
    id: "eashwara",
    name: "EASHWARA PRASADH",
    role: "Project Manager OF NUTECH",
    department: "IST ATHENA",
    photoUrl: "https://picsum.photos/seed/eashwara/100/100",
    managerId: "priyadharshini",
    color: "#BEF264",
    displayOrder: 3,
  },
  {
    id: "yuvaraj",
    name: "Yuvaraj",
    role: "Lead",
    department: "IST ATHENA",
    photoUrl: "/assets/employees/yuvaraj.png",
    managerId: "eashwara",
    color: "#BEF264",
    displayOrder: 4,
  },
  ...["Shrimathi", "Darshan", "Arjun", "Prasanna", "Deepshika", "Haritha", "Devasenatipathi"].map((name, i) => ({
    id: `athena-${i}`,
    name,
    role: "Team Member",
    department: "IST ATHENA",
    photoUrl: name === "Arjun" ? "/assets/employees/arjun.png" : 
              name === "Devasenatipathi" ? "/assets/employees/devasenathipathi.png" : 
              `https://picsum.photos/seed/${name}/100/100`,
    managerId: "yuvaraj",
    color: "#BEF264",
    displayOrder: 5 + i,
  })),

  // IST PEGASUS
  {
    id: "ashwika",
    name: "Ashwika",
    role: "Project Manger OF GOTEK / KUMAR AGRO",
    department: "IST PEGASUS",
    photoUrl: "https://picsum.photos/seed/ashwika/100/100",
    managerId: "priyadharshini",
    color: "#FCA5A5",
    displayOrder: 12,
  },
  {
    id: "harita_v",
    name: "Harita Versni",
    role: "Lead(Gotek)",
    department: "IST PEGASUS",
    photoUrl: "https://picsum.photos/seed/harita/100/100",
    managerId: "ashwika",
    color: "#FCA5A5",
    displayOrder: 13,
  },
  ...["Hariharan", "Rakshana", "Fahima"].map((name, i) => ({
    id: `pegasus-g-${i}`,
    name,
    role: "Team Member",
    department: "IST PEGASUS",
    photoUrl: name === "Hariharan" ? "/assets/employees/hariharan.png" : `https://picsum.photos/seed/${name}/100/100`,
    managerId: "harita_v",
    color: "#FCA5A5",
    displayOrder: 14 + i,
  })),
  {
    id: "srivishnu",
    name: "Srivishnu",
    role: "Lead(Kumar Agro)",
    department: "IST PEGASUS",
    photoUrl: "https://picsum.photos/seed/srivishnu/100/100",
    managerId: "ashwika",
    color: "#FCA5A5",
    displayOrder: 17,
  },
  ...["Devasri", "Arul jothi"].map((name, i) => ({
    id: `pegasus-k-${i}`,
    name,
    role: "Team Member",
    department: "IST PEGASUS",
    photoUrl: name === "Arul jothi" ? "/assets/employees/arul jothi.png" : `https://picsum.photos/seed/${name}/100/100`,
    managerId: "srivishnu",
    color: "#FCA5A5",
    displayOrder: 18 + i,
  })),

  // IST DYNAMICS
  {
    id: "sriram",
    name: "Sriram",
    role: "Project Manager OF ALAGANDRA",
    department: "IST DYNAMICS",
    photoUrl: "/assets/employees/sriram.png",
    managerId: "priyadharshini",
    color: "#93C5FD",
    displayOrder: 20,
  },
  {
    id: "maheswaran",
    name: "Maheswaran",
    role: "Lead",
    department: "IST DYNAMICS",
    photoUrl: "/assets/employees/maheshwaran.png",
    managerId: "sriram",
    color: "#93C5FD",
    displayOrder: 21,
  },
  ...["Shailendhirah", "Sithananthan", "Diya", "Sanjay", "Subiksha", "Varshini", "Jaseema"].map((name, i) => ({
    id: `dynamics-${i}`,
    name,
    role: "Team Member",
    department: "IST DYNAMICS",
    photoUrl: name === "Sanjay" ? "/assets/employees/sanjay.png" : `https://picsum.photos/seed/${name}/100/100`,
    managerId: "maheswaran",
    color: "#93C5FD",
    displayOrder: 22 + i,
  })),

  // IST NEXUS
  {
    id: "yusuf",
    name: "Yusuf",
    role: "Project Manager OF RATE 4 GOLD",
    department: "IST NEXUS",
    photoUrl: "https://picsum.photos/seed/yusuf/100/100",
    managerId: "priyadharshini",
    color: "#C084FC",
    displayOrder: 30,
  },
  {
    id: "dhipak",
    name: "Dhipak",
    role: "Lead",
    department: "IST NEXUS",
    photoUrl: "/assets/employees/dhipak.png",
    managerId: "yusuf",
    color: "#C084FC",
    displayOrder: 31,
  },
  ...["Arpit", "Nithish", "Manikandan", "Shivani", "Purushoth", "Nithish_2", "Swedha Sri", "Monikka"].map((name, i) => ({
    id: `nexus-${i}`,
    name: name.replace("_2", ""),
    role: "Team Member",
    department: "IST NEXUS",
    photoUrl: name === "Purushoth" ? "/assets/employees/purushoth.png" : 
              name === "Nithish" ? "/assets/employees/nithesh s.png" : 
              name === "Nithish_2" ? "/assets/employees/niteesh s.png" : 
              name === "Swedha Sri" ? "/assets/employees/swetha sri.png" : 
              `https://picsum.photos/seed/${name}/100/100`,
    managerId: "dhipak",
    color: "#C084FC",
    displayOrder: 32 + i,
  })),

  // IST R & D
  {
    id: "kollati",
    name: "Kollati",
    role: "Porject Manager OF GOTEK (Lanyard Designing)",
    department: "IST R & D",
    photoUrl: "https://picsum.photos/seed/kollati/100/100",
    managerId: "priyadharshini",
    color: "#FB923C",
    displayOrder: 40,
  },
  {
    id: "praveen",
    name: "Praveen",
    role: "Lead",
    department: "IST R & D",
    photoUrl: "https://picsum.photos/seed/praveen/100/100",
    managerId: "kollati",
    color: "#FB923C",
    displayOrder: 41,
  },
  {
    id: "vysakhi",
    name: "Vysakhi",
    role: "Team Member",
    department: "IST R & D",
    photoUrl: "https://picsum.photos/seed/vysakhi/100/100",
    managerId: "praveen",
    color: "#FB923C",
    displayOrder: 42,
  },

  // IST VERTEX
  ...["Madhesh", "Anjali", "Nitesh", "Harini", "Daksh", "Prasana Vengates", "Vishveshwar", "Jayasuriya"].map((name, i) => ({
    id: `vertex-${i}`,
    name,
    role: "Team Member (Bench)",
    department: "IST VERTEX",
    photoUrl: name === "Prasana Vengates" ? "/assets/employees/prasanna venkatesh.png" : 
              name === "Vishveshwar" ? "/assets/employees/vishweshwar.png" : 
              name === "Jayasuriya" ? "/assets/employees/jayasurya.png" : 
              `https://picsum.photos/seed/${name}/100/100`,
    managerId: "priyadharshini",
    color: "#E5E7EB",
    displayOrder: 50 + i,
  })),
];

export const DEPARTMENTS = [
  { name: "Executives", color: "#FCD34D" },
  { name: "IST ATHENA", color: "#BEF264" },
  { name: "IST PEGASUS", color: "#FCA5A5" },
  { name: "IST DYNAMICS", color: "#93C5FD" },
  { name: "IST NEXUS", color: "#C084FC" },
  { name: "IST R & D", color: "#FB923C" },
  { name: "IST VERTEX", color: "#E5E7EB" },
];
